# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floger', '0003_remove_flog_ingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient_amount',
            name='flog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='floger.Flog'),
            preserve_default=False,
        ),
    ]
