# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floger', '0005_flog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flog',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
